FROM mcr.microsoft.com/dotnet/aspnet:8.0

RUN apt-get update

RUN apt-get install -y gss-ntlmssp

RUN apt-get update && apt-get install -y locales && rm -rf /var/lib/apt/lists/* \
    && sed -i -e 's/# es_BO.UTF-8 UTF-8/es_BO.UTF-8 UTF-8/' /etc/locale.gen \
    && locale-gen

RUN apt-get install -y ca-certificates

COPY ./bsol.crt /usr/local/share/ca-certificates

RUN update-ca-certificates

ENV TZ=America/La_Paz
ENV LANG es_BO.UTF-8  
ENV LANGUAGE es_BO:es  
ENV ASPNETCORE_URLS=http://*:8080

WORKDIR /app

EXPOSE 8080

COPY "app/publish" .

RUN sed -i '/\[openssl_init\]/a ssl_conf = ssl_sect' /etc/ssl/openssl.cnf
RUN printf "\n[ssl_sect]\nsystem_default = system_default_sect\n" >> /etc/ssl/openssl.cnf
RUN printf "\n[system_default_sect]\nMinProtocol = TLSv1.2\nCipherString = DEFAULT@SECLEVEL=0" >> /etc/ssl/openssl.cnf
ENTRYPOINT ["dotnet", "Bsol.Business.Template.Api.dll"]